EXECUTE ad_dd.register_table('XXHR', 'XXHR_PER_SOCIETIES', 'T');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'SOCIETY_ID',1, 'NUMBER', 38, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'CODE',2, 'VARCHAR2', 20, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'DATE_START', 3, 'DATE', 9, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'DATE_END', 4, 'DATE', 9, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'SUBS_AMOUNT', 5, 'VARCHAR2', 20, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'SUBS_PERIOD', 6, 'VARCHAR2', 20, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'SUBS_TOTAL', 7, 'VARCHAR2', 20, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'SUBS_HOLD',8, 'VARCHAR2', 10, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE_CATEGORY',9, 'VARCHAR2', 30, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE1', 10, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE2', 11, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE3', 12,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE4', 13,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE5', 14,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE6', 15,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE7', 16,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE8', 17, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE9', 18, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE10', 19,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE11', 20,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE12', 21,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE13', 22,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE14', 23,'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE15', 24, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE16', 25, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE17', 26, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE18', 27, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE19', 28, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'ATTRIBUTE20', 29, 'VARCHAR2', 150, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'LAST_UPDATE_DATE', 30,'DATE', 9, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'LAST_UPDATED_BY', 31,'NUMBER', 15, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'LAST_UPDATE_LOGIN', 32,'NUMBER', 15, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'CREATED_BY', 33,'NUMBER', 15, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'CREATION_DATE', 34,'DATE', 9, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PER_SOCIETIES', 'PERSON_ID', 35,'NUMBER', 10, 'N', 'N');